version: '3.4'

services:
  pdv.api:
    image: pdvapi
    ports:
    - "7777:80"
    build:
      context: .
      dockerfile: PdvApi/Dockerfile
    depends_on:
      - postgres
 
  postgres:
      image: kartoza/postgis:12.0
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
           POSTGRES_USER: postgres
           POSTGRES_PASS: admin
           POSTGRES_DBNAME: postgres

  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"